---
apiVersion: pcc.paloaltonetworks.com/v1alpha1
kind: Console
metadata:
  name: pcc-console
  namespace: twistlock
spec:
  namespace: twistlock
  orchestrator: kubernetes
  version: '21_08_520'
  consoleConfig:
    serviceType: ClusterIP
